project:
  type: website
  output-dir: "docs"

website:
  title: "Sampling_Cores_Carbon"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Bourgneuf_Bay.qmd
        text: Bourngeuf Bay
      - href: Cadiz_Bay.qmd
        text: Cadiz Bay
format:
  html:
    theme:
      - sandstone
    css: styles.css
    toc: true

editor: visual

