---
title: "Where to perform the coring in each sites ?"
editor_options: 
  chunk_output_type: console
---

::: {style="text-align: center; margin-top: 20px;"}
<button onclick="window.open(&#39;https://github.com/SigOiry/Coring_Carbon_Seagrasses&#39;, &#39;_blank&#39;);" style="padding: 10px 20px; background-color: #4CAF50; color: white; border: none; border-radius: 5px; cursor: pointer;">

Visit the Github repository

</button>
:::

This website gathers all the processing steps used to identify the densest, most recent, and most consistent seagrass patches across different sites, in order to plan future coring strategies.

It gathers analysis done on two sites, Cadiz Bay in Spain ain a nd Bourgneuf Bay in France.

```{r leafletmap}
#| fig-cap: Map of study sites, where coring will be perform in the frame of the Rewrite Project. 
#| echo: false
#| error: false
#| message: false
#| warning: false
#| out-width: "95%"

library(leaflet)
library(htmlwidgets)
library(jsonlite)


coords <- data.frame(
  name  = c("Bourgneuf Bay, France", "Cádiz Bay, Spain", "Ria de Aveiro, Portugal"),
  lat   = c(47.11667, 36.53333, 40.695798

),
  lng   = c(-2.15000,  -6.30000, -8.670350),
  label = c("Bourgneuf Bay",    "Cádiz Bay", "Ria de Aveiro Lagoon"),
  url     = c("https://sigoiry.github.io/Coring_Carbon_Seagrasses/Bourgneuf_Bay.html",
              "https://sigoiry.github.io/Coring_Carbon_Seagrasses/Cadiz_Bay.html",
              "https://sigoiry.github.io/Coring_Carbon_Seagrasses/Aveiro_Lagoon.html"),
  xOffset = c(0,  0,0),    
  yOffset = c(-30, -30,-30),
  stringsAsFactors = FALSE
)


json_data <- toJSON(coords, dataframe = "rows", auto_unbox = TRUE)

m <- leaflet(coords) %>%
  addProviderTiles(providers$Esri.WorldImagery) %>%
  fitBounds(
    lng1 = min(coords$lng), lat1 = min(coords$lat),
    lng2 = max(coords$lng), lat2 = max(coords$lat)
  )

for(i in seq_len(nrow(coords))) {
  m <- m %>%
    addMarkers(
      lng        = coords$lng[i], 
      lat        = coords$lat[i],
      layerId    = coords$label[i],
      label      = coords$label[i],
      labelOptions = labelOptions(
        noHide    = TRUE,
        direction = "top",
        offset    = c(coords$xOffset[i], coords$yOffset[i]),
        style     = list(
          "background"    = "white",
          "padding"       = "3px 6px",
          "border-radius" = "4px",
          "box-shadow"    = "0 0 2px rgba(0,0,0,0.5)"
        )
      )
    )
}

m %>% onRender(
  sprintf(
"function(el, x) {
   // parse our R data.frame as JS array of objects
   var data = %s;
   this.eachLayer(function(layer) {
     // only consider our markers (they all have layerId set)
     if(layer.options && layer.options.layerId) {
       // find matching record by label
       var rec = data.find(function(d){ return d.label === layer.options.layerId; });
       if(rec && rec.url) {
         layer.on('click', function() {
           window.open(rec.url, '_blank');
         });
       }
     }
   });
}", 
    json_data
  )
)
```

# Methodology {#sec-Methodology}

## Images Downloading and preprocessing

For Landsat and SPOT imagery, we refer to the methodology described by [Zoffoli et al. (2021)](https://doi.org/10.1016/j.ecolind.2021.108033). 

Sentinel-2 images were downloaded from the ESA [Copernicus](https://browser.dataspace.copernicus.eu) plateform. For each study site, images were manually inspected to ensure they were cloud-free and acquired during low tide conditions. One image per year was selected, preferably around the date of maximum meadow extent as reported by [Davies et al. (2024)](https://www.nature.com/articles/s43247-024-01543-z). 
To minimize interannual variability, images from the same Sentinel-2 tile were selected for each site. All images selected were pre-processed using baseline version 4.00 or higher. Consequently, 1000 was subtracted from the raw reflectance values of each band to obtain usable surface reflectance values ([More info](https://forum.step.esa.int/t/changes-in-band-data-after-25-jan-2022-baseline-04-00-harmonizevalues-sentinel-2-l2a-snappy/36270)). 

## Images processing

All image processing was performed in R, using the *terra* and *tidyverse* packages.Maps were generated using the *leaflet* package.

### Seagrass Percent Cover
The methodology applied in this study is adapted from [Zoffoli et al. (2021)](https://doi.org/10.1016/j.ecolind.2021.108033). 

Seagrass Percentage Cover (SPC) was derived from the NDVI using the equation established by [Zoffoli et al. (2020)](https://doi.org/10.1016/j.rse.2020.112020):

$$
SPC = 172.06 * NDVI - 22.18
$$

Pixels with SPC values below 20% were excluded from the analysis, due to the high risk of misclassification with other vegetation types. After applying the transformation, pixels with exceptionally high NDVI occasionally resulted in SPC values exceeding 100%. These were capped at 100%.

### Historical seagrass patches of the meadow
To identify consistent high-coverage areas within the meadow, we calculated the number of consecutive years—starting from 2024—in which each pixel exhibited an SPC above 50%. For example, a value of 0 indicates that in 2024 the SPC was below 50%, while a value of 5 means that SPC exceeded 50% every year since 2019 (i.e., 2024 − 5), but not in 2018.

### Year of the maximum of cover

For each pixel, the year corresponding to its maximum SPC value during the time series was identified and recorded.

### Rate of decline since the date of maximum

Starting from the year of maximum SPC, a linear regression was fitted for each pixel to model SPC change over time. The slope of the regression line, when statistically significant (p-value < 0.05), was assigned as the pixel's rate of decline (expressed as percent cover change per year).